# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'DFBaseDemocOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'DFEmpty'
  pod 'MJRefresh'
  
  
  pod 'UMCCommon'
  # U-Share SDK UI模块（分享面板，建议添加）
  pod 'UMCShare/UI'
  # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'

  # Pods for DFBaseDemocOC

end
